seed: 1
variant:
  env: QuadrotorEnv
  env_param:
    obs_repr : nxyz_vxyz_R_omega_reached
    num_goals: 1
    min_goal_dist: 0.2
    max_goal_dist: 1
    goal_tolerance: 0.05
    dynamics_params: Crazyflie
    dynamics_change:
      noise:
        thrust_noise_ratio: 0.05
      damp:
        vel: 0.
        omega_quadratic: 0.
    init_random_state: True
    sim_freq: 200 #Hz
    sim_steps: 2
    ep_time: 7
    sense_noise: default
    rew_type: bare_minimum #epsilon # all_goal_active # current_goal_active # epsilon
    rew_coeff:
      pos: 0. 
      pos_log_weight: 0.
      pos_linear_weight: 0.
      multi_goal_scaling: 2.
      effort: 0.05
      spin: 0.1
      vel: 0.0
      crash: 1.
      orient: 0.
      yaw: 0.
  alg_class: PPO
  alg_param:
    batch_size: 35000
    max_path_length: 700
    n_itr: 5000 #Max num of iterations
    max_samples: 10000000000 #Max num of samples
    discount: 0.99
    step_size: 0.01
    clip_range: 0.05
    optimizer_args: 
      batch_size: 128
      max_epochs: 20
    plot: False
    store_paths: False
    play_every_itr: null
    record_every_itr: 1
  baseline_class: GaussianMLPBaseline
  baseline_param: {} 
  policy_class: GaussianMLPPolicy
  policy_param:
    hidden_sizes: [64, 64]
